# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5df781464df54db1d040eef2e95f3688d616be5328dfd5504da94a0a377c5f0c2dd24f0b328e314b18a07823d60477ec1f8cf328725d97b520f86da3ad819b85

test:
  secret_key_base: dcc3f87e93c93849a65f280bf2952496a330d9054d6cedc69bfbc1bdbc966d97a6366dd11f2e94c2842c72e49bdc52e9983bab6a0e4e876df3bcb45b0ff3f451

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
